POST http://localhost:9080/register HTTP/1.1
content-Type: application/json

{
  "username":"Sumit",
  "password":"Verma",
  "email":"vermaSumit1046@gmail.com",
  "name":"Sumit Verma"
  
}

# {
    
#   "username": "Rahul",
#   "password": "Sharma",
#   "email": "RahulSharma@gmail.com",
#   "name": "Rahul Sharma"

# }

###

POST http://localhost:9080/login HTTP/1.1
content-Type: application/json

{
    
  "email":"vermaSumit1046@gmail.com",
  "password": "Verma"

}
###
POST http://localhost:9080/login HTTP/1.1
content-Type: application/json

{
    
  "email":"RahulSharma@gmail.com",
  "password": "Sharma"

}


###

GET http://localhost:9080/get_user_and_profile
Content-Type:application/json

{
  "token":"fb9ef3ff7ae69655d6aed2b77471ff9514810d402f27b2a51be081ece970033f"
}


### 

POST http://localhost:9080/update_profile_data 
Content-Type: application/json

{
  "token":"fb9ef3ff7ae69655d6aed2b77471ff9514810d402f27b2a51be081ece970033f",
  "bio":"",
  "currentPost":"CTO",
  "pastWork":[
    {
      "company":"Microsoft",
      "position":"CTO",
      "years":"2+"
    }
  ],
  "education" :[
    {
      "school":"IIIT",
      "degree":"B.TECH",
      "fieldOfStudy":"2015-2019"
    }
  ]
}

###
GET http://localhost:9080/user/get_all_user
Content-Type: application/json

